version: "4"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      STRING_SESSION: $STRING_SESSION
      HEROKU_MODE: $HEROKU_MODE
      BOT_USERNAME: $BOT_USERNAME
      SUPPORT: $SUPPORT
      CHANNEL: $CHANNEL
      START_IMG: $START_IMG
      CMD_IMG: $CMD_IMG